### ISSUE TITLE
Make fields in `options` object optional

### ISSUE THREAD

**Issue by ilyachase** [automician/playright#6]
In some methods, there's `options` object, and when passed, it requires all the fields to be passed. Example with `Element.type` method:
```
await this.searchInput.type(search, { delay: 100, noWaitAfter: false });
```
It would be more convenient to pass only needed parameters:
```
await this.searchInput.type(search, { delay: 100 });
```

**Comment by alex-popov-tech** [comment]
@ilyachase done in `0.0.21`
